### ISSUE TITLE
gen_range does not produce evenly distributed values

### ISSUE THREAD

**Issue by tatref** [not-fl3/quad-rand#12]
Issues with the current code:

- Extreme values are very unlikely
- 0 is twice as probable as other values

Test code using the code from latest commit 275af6cc3dcdce5079051e6187a722cf58ab7577
For simplicity, I changed:
- Loop over every possible rand value, count values into buckets
- u32 -> u16 so the code runs more quickly
- use i32 for output, but the code should work the same for other types

```
fn main() {
    const low: i32 = -5;
    const high: i32 = 5;

    let mut counters = [0i32; (high - low + 1) as usize];

    for rand in 0..u16::MAX {
        let r = rand as f64 / (u16::MAX as f64 + 1.0);
        let r = low as f64 + (high as f64 - low as f64) * r;
        let val = r as i32;
        counters[(val - low) as usize] +=1;
    }
    
    dbg!(counters);
}
```

Output
```
[src/main.rs:31] counters = [
    1,            // -5
    6553,         // -4
    6554,         // -3
    6553,         // -2
    6554,         // -1
    13107,        // 0
    6554,         // 1
    6553,         // 2
    6554,         // 3
    6552,         // 4
    0,            // 5
]
```

Fixed code (there's probably a better method than 4.999999...
```
fn main() {
    const low: i32 = -2;
    const high: i32 = 2;

    let mut counters = [0i32; (high-low+1) as usize];

    for rand in 0..u16::MAX {
        let r = rand as f64 / (std::u16::MAX as f64 + 1.);
        let r = (low as f64 - 0.499999) + (high as f64 - low as f64 + 1.) * r;
        let val = r.round() as i32;

        counters[(val - low) as usize] +=1;
    }

    dbg!(counters);
}
```

Output:
```
[src/main.rs:15] counters = [
    13108,
    13107,
    13107,
    13107,
    13106,
]
```

Playground link with both test codes https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=5c62b29747f0e951248f37ed4252b07a

I am not sure it a clean solution, but at least the values are balanced.
Let me know what you think, and I'll submit a PR

**Comment by not-fl3** [comment]
Looks like a legit bug, feel free to submit a PR! 

As an alternative solution I would consider to glean oorandom's implementation (https://hg.sr.ht/~icefox/oorandom/browse/src/lib.rs?rev=tip), its just a lot better/faster than what quad-rand is doing.

**Comment by Bytekeeper** [comment]
As described, vdrn fixed it in their last commit to this repo:
Before:
```Rust
impl RandomRange for u32 {
    fn gen_range(low: Self, high: Self) -> Self {
        let r = rand() as f32 / std::u32::MAX as f32;
        let r = low as f32 + (high as f32 - low as f32) * r;
        r as u32
    }
}```
After:
```Rust
  impl RandomRange for $ty{
        #[inline]
        fn gen_range(low: Self, high: Self) -> Self {
          let r = rand() as f64 / (u32::MAX as f64 + 1.0);
          let r = low as f64 + (high as f64 - low as f64) * r;
          r as Self
        }
      }
```
Note the +1.0 that was added, it will no longer spit out the high value. 
But people using the crates.io version of this crate will still get the error.
@not-fl3 I think you can close this and #13 - but a new release might help prevent confusion in the future.
