### ISSUE TITLE
QuadRand should store RNG state internally

### ISSUE THREAD

**Issue by martin-t** [not-fl3/quad-rand#4]
If there are 2 separate `QuadRand` objects, they should behave as separate RNGs - if i am reading the code right, they would currently use the same global state.

**Comment by bsikar** [comment]
I know this issue is old, but I just now found out and I agree.

**Comment by profan** [comment]
I've just run into this issue (my model tick needs randomness, but the view also uses the same rng and so it leads to nondeterminism in my game state) and it doesn't seem like there's a way right now to have multiple independent rngs that don't just use the same global state, I might have a look at implementing this as I'd also like to avoid pulling an extra dependency on rand in my game if possible

And it seems like someone has even implemented it in: https://github.com/not-fl3/quad-rand/pull/11 already
